spring:
  application:
    name: ai-service
    version: @project.version@
  profiles:
    active: home
  webflux:
    base-path: "/home"

server:
  port: 6200

logbook:
  format:
    style: http

logging:
  level:
    org.zalando.logbook: trace

langchain4j:
  open-ai:
    chat-model:
      api-key: ${openai-token}
      model-name: gpt-4o-mini

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 6004
management:
  server:
    port: 8004